name: 'Setup smalltalkCI'
description: 'Set up smalltalkCI for testing Smalltalk projects'
author: 'Software Architecture Group, Hasso Plattner Institute'
inputs:
  smalltalk-version:
    description: 'Smalltalk image selection (see smalltalkCI''s list of
      supported images)'
    required: true
outputs:
  smalltalk-version:
    description: 'Smalltalk image selection'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'blue'
