name: "CI"
on: [push, pull_request]

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test

  self-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
    - uses: actions/checkout@v1
    - uses: hpi-swa/setup-smalltalkCI@v1
      with:
        smalltalk-version: 'Squeak64-trunk'
    - if: runner.os != 'Windows'
      run: |
        smalltalkci --help
        [[ ! -z "${SMALLTALK_CI_HOME}" ]] || ( echo "SMALLTALK_CI_HOME not set" && false )
    - shell: bash
      if: runner.os == 'Windows'
      run: smalltalkci --help