name: "CI"
on: [push, pull_request]

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test

  self-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: hpi-swa/setup-smalltalkCI@v1
      with:
        smalltalk-version: 'Squeak64-trunk'
    - run: |
        smalltalkci --help
        [[ ! -z "${SMALLTALK_CI_HOME}" ]] || false
